---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: td-agent-barito
  labels:
    app: td-agent-barito
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: td-agent-barito
  labels:
    app: td-agent-barito
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: td-agent-barito
  labels:
    app: td-agent-barito
subjects:
- kind: ServiceAccount
  name: td-agent-barito
  namespace: namespace
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: td-agent-barito
  apiGroup: ""

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: td-agent-barito
  name: td-agent-barito
spec:
  template:
    metadata:
      labels:
        app: td-agent-barito
    spec:
      serviceAccountName: td-agent-barito
      containers:
        - image: barito/td-agent-barito-kubernetes:latest
          imagePullPolicy: Always
          name: td-agent-barito
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            -
              mountPath: /var/log
              name: varlog
            -
              mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
      volumes:
        -
          hostPath:
            path: /var/log
          name: varlog
        -
          hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
