---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: td-agent-barito-daemonset
  namespace: kube-system
  labels:
    k8s-app: td-agent-barito-daemonset
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: td-agent-barito-daemonset
  labels:
    k8s-app: td-agent-barito-daemonset
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: td-agent-barito-daemonset
  labels:
    k8s-app: td-agent-barito-daemonset
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: td-agent-barito-daemonset
  namespace: kube-system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: td-agent-barito-daemonset
  apiGroup: ""

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: td-agent-barito-daemonset
  name: td-agent-barito-daemonset
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: td-agent-barito-daemonset
        version: v1
    spec:
      serviceAccountName: td-agent-barito-daemonset
      containers:
        - image: td-agent-barito-kubernetes:latest
          # Uncomment this if you want to use local build
          #imagePullPolicy: Never
          name: td-agent-barito-daemonset
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            -
              mountPath: /var/log
              name: varlog
            -
              mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
      volumes:
        -
          hostPath:
            path: /var/log
          name: varlog
        -
          hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
