apiVersion: {{ template "daemonset.apiVersion" . }}
kind: DaemonSet
metadata:
  labels:
    app: {{ template "td-agent-barito.name" . }}
  name: {{ template "td-agent-barito.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
{{- if semverCompare ">=1.15.0-0" .Capabilities.KubeVersion.GitVersion }}
  selector:
    matchLabels:
      app: {{ template "td-agent-barito.name" . }}
{{- end }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "td-agent-barito.name" . }}
        release: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/tdagentbaritoconfig.yaml") . | sha256sum }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "td-agent-barito.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      containers:
        - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          name: {{ template "td-agent-barito.fullname" . }}
          ports:
            - name: metrics
              containerPort: 24231
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            tcpSocket:
              port: metrics
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
              ephemeral-storage: {{ .Values.resources.limits.ephemeralStorage }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
              ephemeral-storage: {{ .Values.resources.requests.ephemeralStorage }}
          volumeMounts:
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
            - mountPath: /etc/td-agent
              name: td-agent-barito-config
            {{- if .Values.extraVolumeMounts }}
            {{ toYaml .Values.extraVolumeMounts | trim | nindent 12 }}
            {{ end }}
      volumes:
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
        - name: td-agent-barito-config
          configMap:
            name: {{ template "td-agent-barito.fullname" . }}
        {{- if .Values.extraVolumes  }}
        {{ toYaml .Values.extraVolumes | trim | nindent 8 }}
        {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
