apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: {{ template "td-agent-barito.name" . }}
  name: {{ template "td-agent-barito.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "td-agent-barito.name" . }}
        release: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
    spec:
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "td-agent-barito.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      containers:
        - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          name: {{ template "td-agent-barito.fullname" . }}
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
            - mountPath: /etc/td-agent
              name: td-agent-config
      volumes:
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
        - name: td-agent-config
          configMap:
            name: td-agent-config
