apiVersion: v1
kind: ConfigMap
metadata:
  name: td-agent-barito-config
  namespace: {{ .Release.Namespace }}
data:
  td-agent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      <parse>
        @type none
      </parse>
      read_from_head false
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      annotation_match ["barito.+","fluentd.+"]
      de_dot false
    </filter>

    <filter kubernetes.**>
      @type grep
      <or>
        <regexp>
          key $["kubernetes"]["annotations"]["barito.active"]
          pattern "^true$"
        </regexp>
        <regexp>
          key $["kubernetes"]["annotations"]["fluentd.active"]
          pattern "^true$"
        </regexp>
      </or>
    </filter>

    {{- range .Values.apps }}
    <match kubernetes.var.log.containers.{{ .name }}-**.log>
      @type barito_batch_k8s
      name {{ .name }}
      application_group_secret {{ .applicationGroupSecret }}
      application_name {{ .baritoAppName }}
      produce_url {{ .produceUrl }}
      <buffer>
        flush_at_shutdown {{ $.Values.defaultAgentOptions.buffer.flushAtShutdown }}
        flush_thread_count {{ $.Values.defaultAgentOptions.buffer.flushThreadCount }}
        flush_thread_interval {{ $.Values.defaultAgentOptions.buffer.flushThreadInterval }}
        flush_thread_burst_interval {{ $.Values.defaultAgentOptions.buffer.flushThreadBurstInterval }}
        flush_mode {{ $.Values.defaultAgentOptions.buffer.flushMode }}
        flush_interval {{ $.Values.defaultAgentOptions.buffer.flushInterval }}
        queued_chunks_limit_size {{ $.Values.defaultAgentOptions.buffer.queuedChunksLimitSize }}
        overflow_action {{ $.Values.defaultAgentOptions.buffer.overflowAction }}
        retry_timeout {{ $.Values.defaultAgentOptions.buffer.retryTimeout }}
        retry_max_times {{ $.Values.defaultAgentOptions.buffer.retryMaxTimes }}
        disable_chunk_backup {{ $.Values.defaultAgentOptions.buffer.disableChunkBackup }}
        {{- range .bufferOptions }}
        {{ . }}
        {{- end }}
      </buffer>
    </match>
    {{- end }}
