image:
  name: barito/td-agent-barito-kubernetes
  tag: 0.2.7
  pullPolicy: Always
tolerations: []
updateStrategy: RollingUpdate

rbac:
  ## If true, create and use RBAC resources
  create: false
  ## Ignored if rbac.create is true
  serviceAccountName: default

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 512Mi

defaultAgentOptions:
  buffer:
    flushAtShutdown: false
    flushThreadCount: 8
    flushThreadInterval: 1.0
    flushThreadBurstInterval: 1.0
    flushMode: interval
    flushInterval: 1s
    queuedChunksLimitSize: 1
    overflowAction: drop_oldest_chunk
    retryTimeout: 0s
    retryMaxTimes: 0
    disableChunkBackup: true
