image:
  name: barito/td-agent-barito-kubernetes
  tag: 0.1.4
  pullPolicy: Always

tolerations: []

updateStrategy: OnDelete

rbac:
  ## If true, create and use RBAC resources
  create: false

  ## Ignored if rbac.create is true
  serviceAccountName: default
